### ISSUE TITLE
Pred-trained weight files for KTH 

### ISSUE THREAD

**Issue by return-sleep** [xjgaocs/Grid-Keypoint-Learning#3]
Thank you for your interesting work.
I wonder if you could share the pre-trained weight files of KTH dataset?

**Comment by Tong-Hao741** [comment]
作者你好，您的工作十分卓越，我看代码utiles.py文件中引入数据集使用了from data.kth import KTH，这个data文件并没有找到，因此无法获取数据集，目前我已经下好KTH数据集，但是不知道您是如何数据预处理的，能否提供data文件呢？十分感谢

**Comment by xjgaocs** [comment]
See here.
https://github.com/edenton/svg

**Comment by Tong-Hao741** [comment]
thank u

**Comment by Tong-Hao741** [comment]
抱歉又来打扰您，代码中KTH的指定目录为'../Dataset/KTH/processed/'，可以截图看下这个文件结构以及processed文件下是avi还是png呢？

**Comment by xjgaocs** [comment]
Following this for changing videos to images.
https://github.com/YuemingJin/TMRNet/tree/main
